language: ruby
rvm:
- '2.3.1'
sudo: false
cache: bundler
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/994cc93494715ae5990f
    on_success: change
    on_failure: always
    on_start: never
