language: ruby
rvm:
- '2.3.1'
sudo: false
cache: bundler
env:
  global:
  - RUBY_GC_HEAP_GROWTH_MAX_SLOTS=300000
  - RUBY_GC_HEAP_INIT_SLOTS=600000
  - RUBY_GC_HEAP_GROWTH_FACTOR=1.25
addons:
  postgresql: '9.4'
before_install:
- source ${TRAVIS_BUILD_DIR}/tools/ci/before_install.sh
script:
- bundle exec bin/rails app:test:providers:lenovo:setup app:test:providers:lenovo
after_script: bundle exec codeclimate-test-reporter
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/994cc93494715ae5990f
    on_success: change
    on_failure: always
    on_start: never
